version: '3.8'
name: 'laravel_8.8_spnk'

services:
  db:
    restart: always
    image: mariadb:latest #mysql:8.0.35
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "shipnick_db"
      MYSQL_USER:     "shipnick"
      MYSQL_PASSWORD: "admin"
      TZ: "Asia/Kolkata"
    volumes:
      - db:/var/lib/mysql
      # Optional
      - ./db_init.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "127.0.0.1:3306:3306"
    # command: mysqld --sql-mode="NO_ENGINE_SUBSTITUTION"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: PhpMyAdmin
    restart: always
    ports:
      - "8089:8080"
    environment:
      - PMA_ARBITRARY: 1
      - PMA_HOST: db
      - PMA_PORT: 3306
    depends_on:
      - db
  web:
    image: nginx:1.26.0-alpine
    restart: always
    depends_on:
      - mainapp
    volumes:
      - ./:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./SSL/shipnick.key:/root/ssl/shipnick.key
      - ./SSL/shipnick.crt:/root/ssl/shipnick.crt
    ports:
      - 80:80
      - 443:443
      # - "0.0.0.0:80:80"
  mainapp:
    restart: always
    depends_on:
      - db
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:8808:8000"
    environment:
      TZ: Asia/Kolkata
    # volumes:
    #   - ./vendor:/var/www/html/vendor

volumes:
  db: {}
  # vendor: {}
