name: Deploy

on:
  push:
    branches: [ prod ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: |
          cd /home/ec2-user/shipnick_2024/shipnick_2024/shipnick_2024 && git pull 
          cp .env.prod .env
          docker-compose up --build -d